defaults:
  - train
  - _self_
  - model: whisper_small_v2

compile: true          # PyTorch 2.0 optimization
precision: 'bf16'         # Enable mixed precision (no/fp16/bf16/fp8)
flash_attention: false  # Enable Flash Attention

data:                  # Data settings
  dataset_type: "ors"
  train_dataset_path: ""
  test_dataset_path: ""
  train_dataset_start: 0
  train_dataset_end: 38689
  test_dataset_start: 38689
  test_dataset_end: 39389
  num_classes: 152680
  add_gamemode_token: false
  add_diff_token: false
  add_mapper_token: false
  add_cs_token: false
  add_year_token: false
  add_hitsounded_token: false  # Add token for whether the map has hitsounds
  add_song_length_token: false  # Add token for the length of the song
  add_song_position_token: false  # Add token for the position of the song in the mapset
  add_descriptors: false
  timing_random_offset: 2
  src_seq_len: 2048
  tgt_seq_len: 2560
  rhythm_weight: 1.0    # Weight of rhythm tokens in the loss calculation
  context_types:       # List of context types to include in the dataset
    - "in": []
      "out": ['${context_type:map}']
  context_weights: [4, 1, 1]    # List of weights for each context type. Determines how often each context type is sampled
  mappers_path: "./datasets/beatmap_users.json"       # Path to file with all beatmap mappers
  add_timing: true      # Interweave timing tokens with the beatmap tokens
  add_out_context_types: false  # Add tokens indicating types of the out context
  add_snapping: true    # Model hit object snapping
  add_timing_points: true  # Model beatmap timing with timing points
  add_hitsounds: true   # Model beatmap hitsounds
  add_pre_tokens: false
  per_track: true
  add_distances: false   # Model hit object distances
  add_positions: true
  position_precision: 4 # Precision of hit object coordinates
  position_split_axes: true  # Split hit object X and Y coordinates into separate tokens
  dt_augment_prob: 0.5   # Probability of augmenting the dataset with DT
  dt_augment_range: [1.25, 1.5]  # Range of DT augmentation
  types_first: false       # Put the type token at the start of the group before the timeshift token
  add_kiai: false        # Model kiai times
  gamemodes: [0, 1, 2, 3]  # List of gamemodes to include in the dataset
  mania_bpm_normalized_scroll_speed: true  # Normalize mania scroll speed by BPM
  add_sv_special_token: true  # Add extra special token for current SV
  add_sv: false  # Model slider velocity in std and ctb
  add_mania_sv: false  # Add mania scroll velocity in map context

dataloader:             # Dataloader settings
  num_workers: 4

optim:                  # Optimizer settings
  name: muon
  base_lr: 2e-2         # Should be scaled with the number of devices present
  total_steps: 32768
  warmup_steps: 0
  lr_scheduler: cosine

