defaults:
  - base_inference
  - inference
  - osut5: train_v31
  - diffusion: v1
  - _self_

model_path: 'OliBomby/Mapperatorinator-v31'  # Path to trained model
diff_ckpt: 'OliBomby/osu-diffusion-v2'
version: 'Mapperatorinator V31'        # Beatmap version
output_type: [TIMING, KIAI, MAP, SV]    # Output type (map, timing)
temperature: 0.9        # Sampling temperature
top_p: 0.9              # Top-p sampling threshold
generate_positions: false
timesteps: [10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]  # The number of timesteps we want to take from equally-sized portions of the original process